class civ_car {
        side = "civ";
        type = "CAR_IN_CONCESS";
        vehicles[] = {
             { "EXILIA_d3s_uaz_3159_AMG", { "", "", -1 } },
             { "EXILIA_d3s_giulia_quad_16", { "", "", -1 } },
             { "EXILIA_d3s_giulietta_quad_16", { "", "", -1 } },
             { "EXILIA_d3s_clubman_11_50", { "", "", -1 } },
             { "EXILIA_d3s_clubman_11", { "", "", -1 } },
             { "EXILIA_d3s_coupeconcept_10", { "", "", -1 } },
             { "EXILIA_d3s_silvia_s15_02", { "", "", -1 } },
             { "EXILIA_d3s_wrx_sti_17", { "", "", -1 } },
             { "EXILIA_d3s_wrx_17", { "", "", -1 } },
             { "EXILIA_d3s_wrx_17_FnF8", { "", "", -1 } },
             { "EXILIA_d3s_srthellcat_15", { "", "", -1 } },
             { "EXILIA_d3s_camaro_ss_16", { "", "", -1 } },
             { "EXILIA_d3s_camaro_zl1_17", { "", "", -1 } },
             { "EXILIA_d3s_camaro_zl1_1le_18", { "", "", -1 } },
             { "EXILIA_d3s_boss_15_payback", { "", "", -1 } },
             { "EXILIA_d3s_boss_15", { "", "", -1 } },
             { "EXILIA_d3s_uaz_3162", { "", "", -1 } },
             { "EXILIA_d3s_uaz_469P_EXP", { "", "", -1 } },
             { "EXILIA_d3s_f85_15_m", { "", "", -1 } },
             { "EXILIA_d3s_escalade_16", { "", "", -1 } },
             { "EXILIA_d3s_tahoe_ltz_08", { "", "", -1 } },
             { "EXILIA_d3s_tahoe_EX", { "", "", -1 } },
             { "EXILIA_d3s_tahoe_limited", { "", "", -1 } },
             { "EXILIA_d3s_durango_18", { "", "", -1 } },
             { "EXILIA_d3s_durango_18_se", { "", "", -1 } },
             { "EXILIA_d3s_explorer_13", { "", "", -1 } },
             { "EXILIA_d3s_explorer_sport_13", { "", "", -1 } },
             { "EXILIA_d3s_raptor_17", { "", "", -1 } },
             { "EXILIA_d3s_raptor_SCR_17", { "", "", -1 } },
             { "EXILIA_d3s_qx56_ht_13", { "", "", -1 } },
             { "EXILIA_d3s_qx56_13_SE", { "", "", -1 } },
             { "EXILIA_d3s_QX60_16", { "", "", -1 } },
             { "EXILIA_d3s_QX60_16_S", { "", "", -1 } },
             { "EXILIA_d3s_cherokee_18_TRCK", { "", "", -1 } },
             { "EXILIA_d3s_pajero_07_PE", { "", "", -1 } },
             { "EXILIA_d3s_kodiaq_17", { "", "", -1 } },
             { "EXILIA_d3s_200_VX_16", { "", "", -1 } },
             { "EXILIA_d3s_ctsv_16", { "", "", -1 } },
             { "EXILIA_d3s_300SRT_12", { "", "", -1 } },
             { "EXILIA_d3s_300C_12", { "", "", -1 } },
             { "EXILIA_d3s_charger_15", { "", "", -1 } },
             { "EXILIA_d3s_crown_98", { "", "", -1 } },
             { "EXILIA_d3s_fiesta_16_230", { "", "", -1 } },
             { "EXILIA_d3s_focus_14_H", { "", "", -1 } },
             { "EXILIA_d3s_focus_17_RS", { "", "", -1 } },
             { "EXILIA_d3s_focus_17_LB", { "", "", -1 } },
             { "EXILIA_d3s_taurus_eco_10", { "", "", -1 } },
             { "EXILIA_d3s_civic_17_S", { "", "", -1 } },
             { "EXILIA_d3s_civic_17_R", { "", "", -1 } },
             { "EXILIA_d3s_q50_14_SE", { "", "", -1 } },
             { "EXILIA_d3s_is_YG", { "", "", -1 } }
        };
    };
