textures[] = {
    { "Any", "civ", {}},
    { "Beige", "civ",{ "\david_import_base\texture\civil\beige.paa"}},
    { "Blanc Platine", "civ",{ "\david_import_base\texture\civil\blanc_de_platine.paa"}},
    { "Blanc", "civ", { "\Exilia_Data\Textures\couleurs\blanc.paa"}},
    { "cafe", "civ",{ "\david_import_base\texture\civil\cafe.paa"}},
    { "grege", "civ",{ "\david_import_base\texture\civil\grege.paa"}},
    { "terre_d_ombre", "civ",{ "\david_import_base\texture\civil\terre_d_ombre.paa"}},
    { "gris_anthracite", "civ",{ "\david_import_base\texture\civil\gris_anthracite.paa"}},
    { "gris_de_payne", "civ",{ "\david_import_base\texture\civil\gris_de_payne.paa"}},
    { "gris_perle", "civ",{ "\david_import_base\texture\civil\gris_perle.paa"}},
    { "Gris", "civ",{ "\Exilia_Data\Textures\couleurs\gris.paa"}},
    { "Carbon", "civ",{ "\Exilia_Data\Textures\couleurs\carbon.paa"}},
    { "noir_d_aniline", "civ",{ "\david_import_base\texture\civil\noir_d_aniline.paa"}},
    { "Noir", "civ",{ "\Exilia_Data\Textures\couleurs\noir.paa"}},
    { "Vert", "civ",{ "\Exilia_Data\Textures\couleurs\vert.paa"}},
    { "Vert fonce", "civ",{ "\Exilia_Data\Textures\couleurs\vertfonce.paa"}},
    { "vert_printemps", "civ",{ "\david_import_base\texture\civil\vert_printemps.paa"}},
    { "Bleu","civ", { "\Exilia_Data\Textures\couleurs\bleu.paa"}},
    { "Bleu Canard", "civ",{ "\david_import_base\texture\civil\bleu_canard.paa"}},
    { "Bleu Ceruleen", "civ",{ "\david_import_base\texture\civil\bleu_ceruleen.paa"}},
    { "Bleu Electrique", "civ",{ "\david_import_base\texture\civil\bleu_electrique.paa"}},
    { "Bleu Guede", "civ",{ "\david_import_base\texture\civil\bleu_guede.paa"}},
    { "Bleu Turquoise", "civ",{ "\david_import_base\texture\civil\bleu_turquoise.paa"}},
    { "Bleu fonce", "civ", { "\Exilia_Data\Textures\couleurs\bleufonce.paa"}},
    { "citron", "civ",{ "\david_import_base\texture\civil\citron.paa"}},
    { "jaune_canari", "civ",{ "\david_import_base\texture\civil\jaune_canari.paa"}},
    { "Jaune", "civ",{ "\Exilia_Data\Textures\couleurs\jaune.paa"}},
    { "citrouille", "civ",{ "\david_import_base\texture\civil\citrouille.paa"}},
    { "cerise", "civ",{ "\david_import_base\texture\civil\cerise.paa"}},
    { "Rouge", "civ",{ "\Exilia_Data\Textures\couleurs\rouge.paa"}},
    { "Rouge fonce", "civ",{ "\Exilia_Data\Textures\couleurs\rougefonce.paa"}},
    { "rouge_coquelicot", "civ",{ "\david_import_base\texture\civil\rouge_coquelicot.paa"}},
    { "Orange", "civ",{ "\Exilia_Data\Textures\couleurs\orange.paa"}},
    { "Rose", "civ",{ "\Exilia_Data\Textures\couleurs\rose.paa"}},
    { "fushia", "civ",{ "\david_import_base\texture\civil\fushia.paa"}},
    { "rose_vif", "civ",{ "\david_import_base\texture\civil\rose_vif.paa"}},
   	{ "zizolin", "civ",{ "\david_import_base\texture\civil\zizolin.paa"}},
    { "Violet", "civ",{ "\Exilia_Data\Textures\couleurs\violet.paa"}},
    { "grenat", "civ",{ "\david_import_base\texture\civil\grenat.paa"}},
    { "leopard", "civ",{ "\david_import_base\texture\camo\leopard.paa"}},
    { "paille", "civ",{ "\david_import_base\texture\camo\paille.paa"}},
    { "argent", "civ",{ "\david_import_base\texture\camo\argent.paa"}},
    { "bronze", "civ",{ "\david_import_base\texture\camo\bronze.paa"}},
    { "belle_plante", "civ",{ "\david_import_base\texture\camo\belle_plante.paa"}},
    { "psychedelique", "civ",{ "\david_import_base\texture\camo\psychedelique.paa"}},
    { "trou_de_balle", "civ",{ "\david_import_base\texture\camo\trou_de_balle.paa"}},
    { "discretion", "civ",{ "\david_import_base\texture\camo\discretion.paa"}},
    { "multicouleur", "civ",{ "\david_import_base\texture\camo\multicouleur.paa"}},
    { "rouille1", "civ",{ "\david_import_base\texture\camo\rouille1.paa"}},
    { "etoile_filante", "civ",{ "\david_import_base\texture\camo\etoile_filante.paa"}},
    { "camo", "civ",{ "\david_import_base\texture\camo\camo.paa"}},
    { "camo1", "civ",{ "\david_import_base\texture\camo\camo1.paa"}},
    { "camo2", "civ",{ "\david_import_base\texture\camo\camo2.paa"}},
    { "camo3", "civ",{ "\david_import_base\texture\camo\camo3.paa"}},
    { "camo4", "civ",{ "\david_import_base\texture\camo\camo4.paa"}},
    { "camo5", "civ",{ "\david_import_base\texture\camo\camo5.paa"}},
    { "camo6", "civ",{ "\david_import_base\texture\camo\camo6.paa"}},
    { "camo7", "civ",{ "\david_import_base\texture\camo\camo7.paa"}},
    { "leopard2", "civ",{ "\david_import_base\texture\camo\leopard2.paa"}},
    { "rouille2", "civ",{ "\david_import_base\texture\camo\rouille2.paa"}}
};